application: infinitymaze-1185
version: 1
runtime: python27
api_version: 1
threadsafe: true

default_expiration: "30d"

handlers:
# Static handlers
- url: /(.*\.css)
  mime_type: text/css; charset=UTF-8
  static_files: _build/\1
  upload: _build/(.*\.css)

- url: /(.*\.html)
  mime_type: text/html; charset=UTF-8
  static_files: _build/\1
  upload: _build/(.*\.html)
  expiration: "1h"

- url: /(.*\.js$)
  mime_type: text/javascript
  static_files: _build/\1
  upload: _build/(.*\.js$)

# image files
- url: /(.*\.(bmp|gif|ico|jpeg|jpg|png))
  static_files: _build/\1
  upload: _build/(.*\.(bmp|gif|ico|jpeg|jpg|png))

# index files
- url: /(.+)/
  static_files: _build/\1/index.html
  upload: _build/(.+)/index.html
  expiration: "15m"

- url: /(.+)
  static_files: _build/\1/index.html
  upload: _build/(.+)/index.html
  expiration: "15m"

# site root
- url: /
  static_files: _build/index.html
  upload: _build/index.html
  expiration: "15m"
