application: www-gwax
version: 1
runtime: python27
api_version: 1
threadsafe: true

default_expiration: "30d"

handlers:
- url: /\.well-known/.*
  script: letsencrypt_handler.app

# Static handlers
- url: /(.*\.(c$|h$))
  mime_type: text/x-c
  static_files: static/\1
  upload: static/(.*\.(c$|h$))

- url: /(.*\.css)
  mime_type: text/css; charset=UTF-8
  static_files: static/\1
  upload: static/(.*\.css)

- url: /(.*\.html)
  mime_type: text/html; charset=UTF-8
  static_files: static/\1
  upload: static/(.*\.html)
  expiration: "1h"
  http_headers:
    X-Narwhal: A small arctic whale. The male has a long tusk.

- url: /(.*\.js$)
  mime_type: text/javascript
  static_files: static/\1
  upload: static/(.*\.js$)

- url: /(.*\.json)
  mime_type: application/json
  static_files: static/\1
  upload: static/(.*\.json)
  expiration: "1h"

- url: /(.*\.pdf)
  mime_type: application/pdf
  static_files: static/\1
  upload: static/(.*\.pdf)

- url: /(.*\.rdf)
  mime_type: application/rdf+xml; charset=UTF-8
  static_files: static/\1
  upload: static/(.*\.rdf)
  expiration: "1d"

- url: /(.*\.txt)
  mime_type: text/plain
  static_files: static/\1
  upload: static/(.*\.txt)

# image files
- url: /(.*\.(bmp|gif|ico|jpeg|jpg|png))
  static_files: static/\1
  upload: static/(.*\.(bmp|gif|ico|jpeg|jpg|png))

# audio files
- url: /(.*\.(mid|midi|mp3|wav))
  static_files: static/\1
  upload: static/(.*\.(mid|midi|mp3|wav))

# video files
- url: /(.*\.(avi|mpg))
  static_files: static/\1
  upload: static/(.*\.(avi|mpg))

# index files
- url: /(.+)/
  static_files: static/\1/index.html
  upload: static/(.+)/index.html
  expiration: "15m"
  http_headers:
    X-Narwhal: A small arctic whale. The male has a long tusk.

- url: /(.+)
  static_files: static/\1/index.html
  upload: static/(.+)/index.html
  expiration: "15m"
  http_headers:
    X-Narwhal: A small arctic whale. The male has a long tusk.

# site root
- url: /
  static_files: static/index.html
  upload: static/index.html
  expiration: "15m"
  http_headers:
    X-Narwhal: A small arctic whale. The male has a long tusk.
